// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/Transport.proto

package org.mytest.test.entity.proto;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string param = 1;</code>
   * @return The param.
   */
  java.lang.String getParam();
  /**
   * <code>string param = 1;</code>
   * @return The bytes for param.
   */
  com.google.protobuf.ByteString
      getParamBytes();
}
