// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/Transport.proto

package org.mytest.test.entity.proto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool result = 1;</code>
   * @return The result.
   */
  boolean getResult();
}
